Config = {
	Zones = {
		['AIRP'] = 'Los Santos International Airport', ['ALAMO'] = 'Alamo Sea', ['ALTA'] = 'Alta',
		['ARMYB'] = 'Fort Zancudo', ['BANHAMC'] = 'Banham Canyon Dr', ['BANNING'] = 'Banning',
		['BEACH'] = 'Vespucci Beach', ['BHAMCA'] = 'Banham Canyon', ['BRADP'] = 'Braddock Pass',
		['BRADT'] = 'Braddock Tunnel', ['BURTON'] = 'Burton', ['CALAFB'] = 'Calafia Bridge',
		['CANNY'] = 'Raton Canyon', ['CCREAK'] = 'Cassidy Creek', ['CHAMH'] = 'Chamberlain Hills',
		['CHIL'] = 'Vinewood Hills', ['CHU'] = 'Chumash', ['CMSW'] = 'Chiliad Mountain State Wilderness',
		['CYPRE'] = 'Cypress Flats', ['DAVIS'] = 'Davis', ['DELBE'] = 'Del Perro Beach',
		['DELPE'] = 'Del Perro', ['DELSOL'] = 'La Puerta', ['DESRT'] = 'Grand Senora Desert',
		['DOWNT'] = 'Downtown', ['DTVINE'] = 'Downtown Vinewood', ['EAST_V'] = 'East Vinewood',
		['EBURO'] = 'El Burro Heights', ['ELGORL'] = 'El Gordo Lighthouse', ['ELYSIAN'] = 'Elysian Island',
		['GALFISH'] = 'Galilee', ['GOLF'] = 'GWC and Golfing Society', ['GRAPES'] = 'Grapeseed',
		['GREATC'] = 'Great Chaparral', ['HARMO'] = 'Harmony', ['HAWICK'] = 'Hawick',
		['HORS'] = 'Vinewood Racetrack', ['HUMLAB'] = 'Humane Labs and Research', ['ISHEIST'] = 'Cayo Perico',
		['JAIL'] = 'Bolingbroke Penitentiary', ['KOREAT'] = 'Little Seoul', ['LACT'] = 'Land Act Reservoir',
		['LAGO'] = 'Lago Zancudo', ['LDAM'] = 'Land Act Dam', ['LEGSQU'] = 'Legion Square',
		['LMESA'] = 'La Mesa', ['LOSPUER'] = 'La Puerta', ['MIRR'] = 'Mirror Park',
		['MORN'] = 'Morningwood', ['MOVIE'] = 'Richards Majestic', ['MTCHIL'] = 'Mount Chiliad',
		['MTGORDO'] = 'Mount Gordo', ['MTJOSE'] = 'Mount Josiah', ['MURRI'] = 'Murrieta Heights',
		['NCHU'] = 'North Chumash', ['NOOSE'] = 'N.O.O.S.E', ['OCEANA'] = 'Pacific Ocean',
		['PALCOV'] = 'Paleto Cove', ['PALETO'] = 'Paleto Bay', ['PALFOR'] = 'Paleto Forest',
		['PALHIGH'] = 'Palomino Highlands', ['PALMPOW'] = 'Palmer-Taylor Power Station', ['PBLUFF'] = 'Pacific Bluffs',
		['PBOX'] = 'Pillbox Hill', ['PROCOB'] = 'Procopio Beach', ['RANCHO'] = 'Rancho',
		['RGLEN'] = 'Richman Glen', ['RICHM'] = 'Richman', ['ROCKF'] = 'Rockford Hills',
		['RTRAK'] = 'Redwood Lights Track', ['SANAND'] = 'San Andreas', ['SANCHIA'] = 'San Chianski Mountain Range',
		['SANDY'] = 'Sandy Shores', ['SKID'] = 'Mission Row', ['SLAB'] = 'Stab City',
		['STAD'] = 'Maze Bank Arena', ['STRAW'] = 'Strawberry', ['TATAMO'] = 'Tataviam Mountains',
		['TERMINA'] = 'Terminal', ['TEXTI'] = 'Textile City', ['TONGVAH'] = 'Tongva Hills',
		['TONGVAV'] = 'Tongva Valley', ['VCANA'] = 'Vespucci Canals', ['VESP'] = 'Vespucci',
		['VINE'] = 'Vinewood', ['WINDF'] = 'Ron Alternates Wind Farm', ['WVINE'] = 'West Vinewood',
		['ZANCUDO'] = 'Zancudo River', ['ZP_ORT'] = 'Port of South Los Santos', ['ZQ_UAR'] = 'Davis Quartz'
	},

	CustomStreets = {
		{ start_x = 296.66, start_y = -237.64, end_x = 354.17, end_y = -182.28, name = 'Urzędnicza Street' },
		{ start_x = 229.6842, start_y = -2178.7263, end_x = 478.8938, end_y = -1959.4221, name = 'Pope John Paul II Street' }
	},
	
	Channels = {
		[1] = "LSPD MAIN",
		[2] = "TAKTYCZNY #1",
		[3] = "TAKTYCZNY #2",
		[4] = "TAKTYCZNY #3",
		[5] = "SAMS MAIN",
		[6] = "SAMS #1",
		[7] = "SAMS #2",
		[8] = "GOVERMENT",
		[9] = "GOV #1",
		[10] = "DOJ #1",
		[11] = "MECHANIK",
		[12] = "MECHANIK #1",
		[13] = "MECHANIK #2",
	}	
}